name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check PHP syntax
        run: |
          find . -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check JS syntax
        run: |
          find public/js -name '*.js' -print0 | xargs -0 -n1 node -c

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: quizproject_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Wait for MySQL to be ready
        run: sleep 15
        
      - name: Vérification debug phpunit
        run: ls -la vendor/bin

      - name: Make migration script executable
        run: chmod +x scripts/migration_test.sh

      - name: Run migration
        run: ./scripts/migration_test.sh


      - name: Run PHPUnit tests
        env:
          DATABASE_DSN: "mysql:host=127.0.0.1;port=3306;dbname=quizproject_test"
          DB_USER: root
          DB_PASSWORD: root
        run: ./vendor/bin/phpunit --configuration phpunit.xml