name: Continuous Integration

on:
  push:
    paths:
      - '**.php'
      - '**.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Check PHP syntax
        run: |
          find . -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Check JS syntax
        run: |
          find public/js -name '*.js' -print0 | xargs -0 -n1 node -c
